import psycopg2
from api_request import mock_data


def connect_to_db():
    #Connection to PostgreSQL database

    print("Connecting to PostgreSQL database..")
    try:
        conn = psycopg2.connect(
            host="host.docker.internal",
            port=5432,
            dbname="weather",
            user="pipeline",
            password="pipeline"
        )
        return conn
    except psycopg2.Error as e:
        print(f"Database connection failed..: {e}")
        raise


def create_table(conn):
    # Creates a table to the database if there is none ..with correct values.
    # Sticking to the same names as weatherstack gives

    print("Creating table if not exist..")
    try:
        cursor = conn.cursor()
        cursor.execute("""
            CREATE SCHEMA IF NOT EXISTS dev;
            CREATE TABLE IF NOT EXISTS dev.raw_weather_data (
                id SERIAL PRIMARY KEY,
                city TEXT,
                temperature FLOAT,
                weather_descriptions TEXT,
                wind_speed FLOAT,
                wind_dir TEXT,
                humidity FLOAT,
                feels_like TEXT,
                time TIMESTAMP,
                inserted_at TIMESTAMP DEFAULT NOW(),
                utc_offset TEXT
            );                                    
        """)
        conn.commit()
        print("Table was created.")
    except psycopg2.Error as e:
        print(f"There was a problem creating table: {e}")    
        raise


def insert_records(conn, data):
    # Inserts current weather data from the Weatherstack API into the dev.raw_weather_data table.
    # Uses field from "location" and "current" objects.
    # inserted_at is generated by Postgresql NOW()

    print(f"Inserting weather data into the database..")
    try:
        weather = data['current']
        location = data['location']
        cursor = conn.cursor()
        cursor.execute("""
            INSERT INTO dev.raw_weather_data (
                city,
                temperature,
                weather_descriptions,
                wind_speed,
                wind_dir,
                humidity,
                feels_like,
                time,
                inserted_at,
                utc_offset           
            ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, NOW(), %s)
        """,(
            location['name'],
            weather['temperature'],
            weather['weather_descriptions'][0], #maybe a safeguard here if there is none
            weather['wind_speed'],
            weather['wind_dir'],
            weather['humidity'],
            weather['feelslike'],
            location['localtime'],
            location['utc_offset']
        ))
        conn.commit()
        print("Data succesfully inserted.")
    except psycopg2.Error as e:
        print(f"There was a problem inserting data: {e}")    
        raise 

def main():
    conn = None
    try:
        data = mock_data()
        conn = connect_to_db()
        create_table(conn)
        insert_records(conn, data)
    except Exception as e:
        print(f"There was an error during execution: {e}")
    finally:
        if conn:
            conn.close()
            print(f"Database connection closed.")

